version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.1-full
    ports:
      - 80:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
  app:
    image: royceltd/rasa-stock-crypto
    ports: 
      - 5055:5055
