version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.1-full
    ports:
      - 80:5005
    volumes:
      - ./:/app
    command:
      - run
      - --enable-api
      - --cors
      - "*"
  app:
    image: royceltd/rasa-stock-crypto
    expose: [5055]
